# Generated by Django 5.1.4 on 2026-03-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_booking_schedule_date_booking_scheduled_date_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='clients.booking'),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
