# Generated by Django 5.1.4 on 2026-03-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_booking_scheduled_date'),
        ('payment', '0002_payment_booking_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='clients.booking'),
        ),
    ]
