# Generated by Django 5.1.4 on 2025-05-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='author')),
                ('comment', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='uploads/images')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer', models.CharField(max_length=100, verbose_name='client')),
                ('tel', models.IntegerField()),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hairstyle')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('tel', models.IntegerField(max_length=9)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('schedule_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hairstyle')),
            ],
        ),
    ]
