# Generated by Django 5.1.4 on 2025-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
