# Generated by Django 5.1.4 on 2026-03-24 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_hairstyle_image_remove_product_image_and_more'),
        ('clients', '0002_alter_order_tel'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.payment')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hairstyle')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
