# Generated by Django 5.1.4 on 2026-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_booking_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='schedule_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(default='YM-23475', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.CharField(max_length=50),
        ),
    ]
