# Generated by Django 5.1.4 on 2026-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_booking_schedule_date_booking_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
