# Generated by Django 5.1.4 on 2026-03-28 16:41

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_booking_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, default=timezone.now),
        ),
    ]
