# Generated by Django 5.1.4 on 2026-03-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_booking_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
