# Generated by Django 5.1.4 on 2026-03-28 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_booking_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2026, 3, 30)),
        ),
    ]
