# Generated by Django 5.1.4 on 2026-03-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_booking_scheduled_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='client',
            new_name='bearer',
        ),
    ]
