# Generated by Django 5.1.4 on 2026-03-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_rename_client_booking_bearer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='style',
            new_name='hairstyle',
        ),
    ]
