# Generated by Django 5.1.4 on 2026-03-28 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_rename_style_booking_hairstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
