# Generated by Django 5.1.4 on 2026-04-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_booking_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
